### ISSUE TITLE
Images have 3 channels, but typical mr/ct scans only have 1

### ISSUE THREAD

**Issue by JonathanBhimani-Burrows** [devavratTomar/sasan#1]
Hi,
I was trying out the saved models as the paper is really interesting, however I noticed that the train/test images have 3 channels. I was wondering if you could comment on this, as most mr/ct scans have 1 dimension. 
Is a valid way around this to stack the single dimension 3 times to match the 3 channels?
Thanks

**Comment by JonathanBhimani-Burrows** [comment]
Answer came via email - very helpful!
"3 channels that are consecutive slices of the 3D volume"

**Comment by iTomxy** [comment]
@JonathanBhimani-Burrows Hi, can you reproduce the result on paper?
